name: Build and publish the package to npm

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Removing unnecessary files
        run: |
          rm -rf .github
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Updating the version to tag name
        run: npm version ${{github.ref_name}} --no-git-tag-version
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Removing unnecessary files
        run: |
          rm -rf .github
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Updating the version to tag name
        run: npm version ${{github.ref_name}} --no-git-tag-version
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}